#include <pebble.h>
#include "index.h"

static Window *s_main_window;

static TextLayer *s_day_layer, *s_date_layer, *s_temperature_layer /*, *s_temperatureSave_layer*/, *s_battery_layer;
static int s_battery_level;

// struct for clay settings (see index.h)
ClaySettings settings;

static AppSync s_sync;

static void load_clay_default_settings(void) {
  settings.ShowBattery = true;
  settings.ShowTemperature = true;
  
  persist_read_data(SETTINGS_KEY, &settings, sizeof(settings));
}
/*
static void display_temperature() {
  if(settings.ShowTemperature) {
    text_layer_set_text(s_temperature_layer, text_layer_get_text(s_temperatureSave_layer));
  }
  else
    text_layer_set_text(s_temperature_layer, "");
}
*/

static void display_battery(BatteryChargeState state) {
  if(settings.ShowBattery) {
    // Record the new battery level
    s_battery_level = state.charge_percent;
    
    static char s_battery[4]; // max. 3 digits
    snprintf(s_battery, sizeof(s_battery), "%u", s_battery_level);
    text_layer_set_text(s_battery_layer, s_battery);
  }
  else
    text_layer_set_text(s_battery_layer, "");
}

static void update_display() {
  display_battery(battery_state_service_peek()); 
  //display_temperature();
}

// Save the settings to persistent storage
static void save_clay_settings() {
  persist_write_data(SETTINGS_KEY, &settings, sizeof(settings));
  update_display();
}

static void inbox_received_callback(DictionaryIterator *iter, void *context) {
  
  // Read weather data
  Tuple *WeatherTemperature_t = dict_find(iter, MESSAGE_KEY_WeatherTemperature);
  if(WeatherTemperature_t) {
    text_layer_set_text(s_temperature_layer, WeatherTemperature_t->value->cstring);    
  }

  // Read clay preferences
  Tuple *ShowBattery_t = dict_find(iter, MESSAGE_KEY_ShowBattery);
  if(ShowBattery_t) {
    settings.ShowBattery = ShowBattery_t->value->int32 == 1;
  }
  
  Tuple *ShowTemperature_t = dict_find(iter, MESSAGE_KEY_ShowTemperature);
  if(ShowTemperature_t) {
    settings.ShowTemperature = ShowTemperature_t->value->int32 == 1;
  }
  
  save_clay_settings();
}

static void inbox_dropped_callback(AppMessageResult reason, void *context) {
  APP_LOG(APP_LOG_LEVEL_ERROR, "Message dropped!");
}

static void outbox_failed_callback(DictionaryIterator *iterator, AppMessageResult reason, void *context) {
  APP_LOG(APP_LOG_LEVEL_ERROR, "Outbox send failed!");
}

static void outbox_sent_callback(DictionaryIterator *iterator, void *context) {
  APP_LOG(APP_LOG_LEVEL_INFO, "Outbox send success!");
}

// Slot on-screen layout:
//     0 1
//     2 3
#define TOTAL_IMAGE_SLOTS 4
#define NUMBER_OF_IMAGES 20

// These images are 72 x 84 pixels (i.e. a quarter of the Aplite display),
// black and white with the digit character centered in the image.
// (As generated by the `fonttools/font2png.py` script.)
const int IMAGE_RESOURCE_IDS[NUMBER_OF_IMAGES] = {
  RESOURCE_ID_IMAGE_NUM_0_THIN, RESOURCE_ID_IMAGE_NUM_1_THIN, RESOURCE_ID_IMAGE_NUM_2_THIN,
  RESOURCE_ID_IMAGE_NUM_3_THIN, RESOURCE_ID_IMAGE_NUM_4_THIN, RESOURCE_ID_IMAGE_NUM_5_THIN,
  RESOURCE_ID_IMAGE_NUM_6_THIN, RESOURCE_ID_IMAGE_NUM_7_THIN, RESOURCE_ID_IMAGE_NUM_8_THIN,
  RESOURCE_ID_IMAGE_NUM_9_THIN,
  
  RESOURCE_ID_IMAGE_NUM_0_REGULAR, RESOURCE_ID_IMAGE_NUM_1_REGULAR, RESOURCE_ID_IMAGE_NUM_2_REGULAR,
  RESOURCE_ID_IMAGE_NUM_3_REGULAR, RESOURCE_ID_IMAGE_NUM_4_REGULAR, RESOURCE_ID_IMAGE_NUM_5_REGULAR,
  RESOURCE_ID_IMAGE_NUM_6_REGULAR, RESOURCE_ID_IMAGE_NUM_7_REGULAR, RESOURCE_ID_IMAGE_NUM_8_REGULAR,
  RESOURCE_ID_IMAGE_NUM_9_REGULAR
};

static GBitmap *s_images[TOTAL_IMAGE_SLOTS];
static BitmapLayer *s_image_layers[TOTAL_IMAGE_SLOTS];

#define EMPTY_SLOT -1

// The state is either "empty" or the digit of the image currently in the slot.
static int s_image_slot_state[TOTAL_IMAGE_SLOTS] = {
  EMPTY_SLOT, EMPTY_SLOT, EMPTY_SLOT, EMPTY_SLOT
};

// Loads the digit image from the application's resources and
// displays it on-screen in the correct location.
// Each slot is a quarter of the screen.
static void load_digit_image_into_slot(int slot_number, int digit_value) {
  GRect bounds = layer_get_bounds(window_get_root_layer(s_main_window));
  GRect tile_bounds = gbitmap_get_bounds(s_images[slot_number]);

  s_image_slot_state[slot_number] = digit_value;
  s_images[slot_number] = gbitmap_create_with_resource(IMAGE_RESOURCE_IDS[digit_value]);

  const int x_offset = (bounds.size.w - (2 * tile_bounds.size.w)) / 2 - 20;
  const int y_offset = (bounds.size.h - (2 * tile_bounds.size.h)) / 2;
  BitmapLayer *bitmap_layer = bitmap_layer_create(
    GRect(x_offset + ((slot_number % 2) * tile_bounds.size.w),
          y_offset + ((slot_number / 2) * tile_bounds.size.h),
          tile_bounds.size.w, tile_bounds.size.h));
  s_image_layers[slot_number] = bitmap_layer;
  bitmap_layer_set_bitmap(bitmap_layer, s_images[slot_number]);

  Layer *window_layer = window_get_root_layer(s_main_window);
  layer_add_child(window_layer, bitmap_layer_get_layer(bitmap_layer));
}

static void unload_digit_image_from_slot(int slot_number) {
  if (s_image_slot_state[slot_number] != EMPTY_SLOT) {
    layer_remove_from_parent(bitmap_layer_get_layer(s_image_layers[slot_number]));
    bitmap_layer_destroy(s_image_layers[slot_number]);
    gbitmap_destroy(s_images[slot_number]);

    // This is now an empty slot
    s_image_slot_state[slot_number] = EMPTY_SLOT;
  }
}

static void display_value(unsigned short value, unsigned short row_number, bool show_first_leading_zero) {
  value = value % 100; // Maximum of two digits per row.    
  
  // Column order is: | Column 0 | Column 1 |
  // (We process the columns in reverse order because that makes
  // extracting the digits from the value easier.)
  for (int column_number = 1; column_number >= 0; column_number--) {
    int slot_number = (row_number * 2) + column_number;
    unload_digit_image_from_slot(slot_number);
    if (!((value == 0) && (column_number == 0) && !show_first_leading_zero)) {
      if(row_number==0)
        load_digit_image_into_slot(slot_number, (value % 10)+10);
      else
        load_digit_image_into_slot(slot_number, value % 10);
    }
    value = value / 10;
  }
}

static unsigned short get_display_hour(unsigned short hour) {
  if (clock_is_24h_style()) {
    return hour;
  }

  // Converts "0" to "12"
  unsigned short display_hour = hour % 12;
  return display_hour ? display_hour : 12;
}

static void display_time(struct tm *tick_time) {
  display_value(get_display_hour(tick_time->tm_hour), 0, true);
  display_value(tick_time->tm_min, 1, true);
}

static void display_day(struct tm *tick_time) {
  switch(tick_time->tm_wday) {
    case 0:
      text_layer_set_text(s_day_layer, "SO");
      break;
    case 1:
      text_layer_set_text(s_day_layer, "MO");
      break;
    case 2:
      text_layer_set_text(s_day_layer, "DI");
      break;
    case 3:
      text_layer_set_text(s_day_layer, "MI");
      break;
    case 4:
      text_layer_set_text(s_day_layer, "DO");
      break;
    case 5:
      text_layer_set_text(s_day_layer, "FR");
      break;
    case 6:
      text_layer_set_text(s_day_layer, "SA");
      break;
    default:
      break;
  }
}

static void display_date(struct tm *tick_time) {
  static char s_date[3]; // max. 2 digits
  if(tick_time->tm_mday < 10)    // leading zero
    snprintf(s_date, sizeof(s_date), "0%u", tick_time->tm_mday);
  else
    snprintf(s_date, sizeof(s_date), "%u", tick_time->tm_mday);
  text_layer_set_text(s_date_layer, s_date);
}

static void handle_minute_tick(struct tm *tick_time, TimeUnits units_changed) {
  display_time(tick_time);
  display_day(tick_time);
  display_date(tick_time);
}

static void main_window_load(Window *window) {
  time_t now = time(NULL);
  struct tm *tick_time = localtime(&now);
  Layer *window_layer = window_get_root_layer(window);
  GRect bounds = layer_get_bounds(window_layer);
  
  // Time
  display_time(tick_time);
  tick_timer_service_subscribe(MINUTE_UNIT, handle_minute_tick);

  // Day
  s_day_layer = text_layer_create(GRect(bounds.size.w/2-25, bounds.size.h/2-23, bounds.size.w, 34));
  text_layer_set_text_color(s_day_layer, GColorWhite);
  text_layer_set_background_color(s_day_layer, GColorClear);
  text_layer_set_font(s_day_layer, fonts_load_custom_font(resource_get_handle(RESOURCE_ID_FONT_INTERSTATE_THIN_18)));
  text_layer_set_text_alignment(s_day_layer, GTextAlignmentCenter);
  layer_add_child(window_layer, text_layer_get_layer(s_day_layer));
  
  // Date
  s_date_layer = text_layer_create(GRect(bounds.size.w/2-25, bounds.size.h/2, bounds.size.w, 34));
  text_layer_set_text_color(s_date_layer, GColorWhite);
  text_layer_set_background_color(s_date_layer, GColorClear);
  text_layer_set_font(s_date_layer, fonts_load_custom_font(resource_get_handle(RESOURCE_ID_FONT_INTERSTATE_REGULAR_18)));
  text_layer_set_text_alignment(s_date_layer, GTextAlignmentCenter);
  layer_add_child(window_layer, text_layer_get_layer(s_date_layer));

  // Battery
  s_battery_layer = text_layer_create(GRect(10, bounds.size.h-18, bounds.size.w, 34));
  text_layer_set_text_color(s_battery_layer, GColorWhite);
  text_layer_set_background_color(s_battery_layer, GColorClear);
  text_layer_set_font(s_battery_layer, fonts_load_custom_font(resource_get_handle(RESOURCE_ID_FONT_INTERSTATE_EXTRA_LIGHT_14)));
  text_layer_set_text_alignment(s_battery_layer, GTextAlignmentLeft);
  // Register for battery level updates
  battery_state_service_subscribe(display_battery);
  layer_add_child(window_layer, text_layer_get_layer(s_battery_layer));
  
  // Temperature
  s_temperature_layer = text_layer_create(GRect(bounds.size.w-34, bounds.size.h-18, bounds.size.w, 34));
  text_layer_set_text_color(s_temperature_layer, GColorWhite);
  text_layer_set_background_color(s_temperature_layer, GColorClear);
  text_layer_set_font(s_temperature_layer, fonts_load_custom_font(resource_get_handle(RESOURCE_ID_FONT_INTERSTATE_EXTRA_LIGHT_14)));
  text_layer_set_text_alignment(s_temperature_layer, GTextAlignmentLeft);
  layer_add_child(window_layer, text_layer_get_layer(s_temperature_layer));
  
  // Ensure clay settings are correctly displayed from the start
  update_display();
}

static void main_window_unload(Window *window) {
  for (int i = 0; i < TOTAL_IMAGE_SLOTS; i++) {
    unload_digit_image_from_slot(i);
  }
  text_layer_destroy(s_day_layer);
  text_layer_destroy(s_date_layer);
  text_layer_destroy(s_temperature_layer);
  text_layer_destroy(s_battery_layer);
}

static void init(void) {
  s_main_window = window_create();
  window_set_background_color(s_main_window, GColorBlack);
  window_set_window_handlers(s_main_window, (WindowHandlers) {
    .load = main_window_load,
    .unload = main_window_unload
  });
  window_stack_push(s_main_window, true);
  
  // load default clay values
  load_clay_default_settings();
  
  // Register callbacks
  app_message_register_inbox_received(inbox_received_callback);
  app_message_register_inbox_dropped(inbox_dropped_callback);
  app_message_register_outbox_failed(outbox_failed_callback);
  app_message_register_outbox_sent(outbox_sent_callback);
  // Open AppMessage
  app_message_open(128, 128);
}

static void deinit(void) {
  window_destroy(s_main_window);
  
  app_sync_deinit(&s_sync);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}